// leave off @2x/@3x
const images = {
  logo: require('../Images/logo.png'),
  bg: require('../Images/delhero.png'),
  marker: require('../Images/marker.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  ekonomIcon: require('../Images/econom.png'),
  comfortIcon: require('../Images/comfort.png'),
  vipIcon: require('../Images/vip.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  news: require('../Images/news1.jpg'),
  news1: require('../Images/News2.jpg'),
  news2: require('../Images/news3.png'),
  letter: require('../Images/letter.png'),
  piyada: require('../Images/pedestrian.png'),
  moto: require('../Images/motorbike.png'),
  avto: require('../Images/car.png'),
  az: require('../Images/Flags/Azerbaijan.png'),
  ru: require('../Images/Flags/Russia.png'),
  us: require('../Images/Flags/United-States-of-America.png'),
  userDefaultImg: require('../Images/user-default-img.png'),
}

export default images
